training_pipeline_config:
  pipeline_name: NewsArticleSorting
  artifact_dir: NAS_Artifact_Dir


data_ingestion_config:
  training_input_dir: NASTrainingDatasets
  prediction_input_dir: NASPredictionDatasets
  training_dir: training_dataset
  prediction_dir: prediction_dataset


data_validation_config:
  schema_dir: config
  schema_file_name: schema.yaml
  validated_dir: validated_dataset


cassandra_database_config:
  training_table_name: good_train_table
  prediction_table_name: good_pred_table
  secure_connect_bundle_directory: NASDatabase
  secure_connect_bundle_filename: secure-connect-ineuron.zip
  environment_key_client_id: CASSANDRA_CLIENT_ID
  environment_key_client_secret: CASSANDRA_CLIENT_SECRET
  keyspace_name: news_article_sorting_internship

data_preprocessing_config:
  preprocessed_dir: preprocessed_dataset 
  ohe_model_dir : pickle_models
  one_hot_encoder_file_name: ohe.pickle


model_training_config:
  trained_model_dir: trained_model
  base_accuracy: 0.2
  model_config_dir: config
  model_config_file_name: model.yaml
  max_seq_length: 256
  padding_type: max_length
  truncation: True
  input_feature: Text


model_evaluation_config:
  evaluation_result_dir: model_evaluation
  eval_batch_size: 4
  base_accuracy: 0.2
  model_evaluation_file_name: model_evaluation.yaml

model_pusher_config:
  model_exposed_dir: ModelSelected
  deployed_model_details: deployed_model_details.yaml
  deployed_model_filename: model.bin