SampleFileName: NAS_07092022_153756
LengthOfDate: 8
LengthOfTime: 6
NunberOfColumns: 3
ColumnNames:
  ArticleId: int
  Text: text

TargetColumn:
  Category: text


TargetColumnValues:
  - business
  - tech
  - sport
  - politics
  - entertainment